/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package modeldb;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ModelRankMetric implements org.apache.thrift.TEnum {
  RMSE(0),
  EXPLAINED_VARIANCE(1),
  R2(2);

  private final int value;

  private ModelRankMetric(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ModelRankMetric findByValue(int value) { 
    switch (value) {
      case 0:
        return RMSE;
      case 1:
        return EXPLAINED_VARIANCE;
      case 2:
        return R2;
      default:
        return null;
    }
  }
}
